# Script to create the soil_structured example dataset
#
# WHY THIS EXISTS
# soil_data and soil_ucayali draw every property independently from rnorm(),
# so they carry no covariance beyond the texture closure applied afterwards.
# The largest off-diagonal Spearman rho in soil_data is 0.66 and exactly one
# pair clears a 0.6 threshold. That makes them unusable for demonstrating any
# method that works on the relationships BETWEEN indicators -- correlation
# network selection, functional grouping, redundancy screening.
#
# This dataset is simulated too, but from latent factors, so that the
# well-established pedological relationships hold:
#
#   Sand + Silt + Clay = 100          compositional closure
#   SOC = OM / 1.724                  van Bemmelen conversion factor
#   N   = SOC / (C:N ratio)           C:N around 11 in cultivated topsoil
#   CEC = f(Clay, OM)                 clay and organic colloids carry charge
#   Ca, Mg = f(CEC, base status)      exchangeable bases occupy CEC sites
#   BD  = f(-OM, +Sand)               organic matter lowers bulk density
#   pH  = f(base status)              base saturation drives reaction
#   EC  = f(Ca + Mg)                  soluble bases carry conductivity
#
# The values remain in realistic ranges for acidic tropical soils of the
# Ucayali region, matching soil_ucayali, so the three datasets are comparable.

set.seed(2026)

n <- 120

# ---- latent factors ---------------------------------------------------------
# Three independent gradients that a real soil survey would sample across.

texture_gradient <- rnorm(n)   # coarse (low) to fine (high)
organic_gradient <- rnorm(n)   # depleted (low) to well supplied (high)
base_gradient    <- rnorm(n)   # strongly weathered/acid (low) to base rich

# ---- particle size ----------------------------------------------------------
# Clay rises and sand falls along the texture gradient. Silt is whatever is
# left, which is what makes the three compositional: they sum to 100 by
# construction, and any two of them determine the third.

Clay <- 24 + 7.5 * texture_gradient + rnorm(n, 0, 2.0)
Clay <- pmin(pmax(Clay, 8), 45)

Sand <- 48 - 8.5 * texture_gradient + rnorm(n, 0, 3.0)
Sand <- pmin(pmax(Sand, 20), 70)

Silt <- 100 - Sand - Clay
# Keep silt physically plausible by pushing any excess back into sand.
too_low <- Silt < 8
Sand[too_low] <- Sand[too_low] - (8 - Silt[too_low])
Silt[too_low] <- 8

# ---- organic fractions ------------------------------------------------------
# OM, SOC and N are three measurements of one underlying pool, which is why
# they are near-collinear in every real soil dataset.

OM <- 3.0 + 1.05 * organic_gradient + 0.18 * texture_gradient +
  rnorm(n, 0, 0.34)
OM <- pmax(OM, 0.6)

# van Bemmelen: organic matter is about 58% carbon.
SOC <- OM / 1.724 * (1 + rnorm(n, 0, 0.04))

# C:N ratio around 11, as in cultivated tropical topsoil.
CN_ratio <- rnorm(n, 11, 1.1)
N <- SOC / CN_ratio

# ---- exchange complex -------------------------------------------------------
# CEC is generated by clay surfaces and organic colloids together, so it is
# the natural hub of the correlation network.

CEC <- 0.28 * Clay + 2.1 * OM + rnorm(n, 0, 0.9)
CEC <- pmax(CEC, 3)

# pH follows base status.
pH <- 5.3 + 0.75 * base_gradient + rnorm(n, 0, 0.22)
pH <- pmin(pmax(pH, 3.9), 7.8)

# Exchangeable bases occupy a share of the exchange sites, and that share
# rises with pH. Keeping the share moderately variable is what makes Ca track
# CEC strongly enough to connect the exchange complex to the base-status
# cluster -- in a real soil calcium dominates the exchange sites, and a
# correlation network that separates Ca from CEC would be an artefact.
base_saturation <- pmin(pmax(0.30 + 0.11 * base_gradient +
                               rnorm(n, 0, 0.025), 0.10), 0.85)
Ca <- CEC * base_saturation * 0.72 + rnorm(n, 0, 0.18)
Ca <- pmax(Ca, 0.3)
Mg <- Ca / 2.9 + rnorm(n, 0, 0.12)
Mg <- pmax(Mg, 0.1)

# ---- bulk density -----------------------------------------------------------
# Organic matter lowers bulk density; sand raises it.

BD <- 1.62 - 0.075 * OM + 0.0035 * Sand + rnorm(n, 0, 0.045)
BD <- pmin(pmax(BD, 0.95), 1.75)

# ---- nutrients --------------------------------------------------------------
# P availability tracks organic matter and is suppressed by acidity through
# iron and aluminium fixation. K tracks the exchange complex.

P <- 2.2 * OM + 1.6 * (pH - 5.0) + rnorm(n, 0, 1.4)
P <- pmax(P, 1.0)

K <- 5.8 * CEC + 3.5 * OM + rnorm(n, 0, 9)
K <- pmax(K, 20)

S <- 3.4 * OM + rnorm(n, 0, 1.6)
S <- pmax(S, 1.0)

# Soluble bases carry the conductivity.
EC <- 0.045 * (Ca + Mg) + rnorm(n, 0, 0.030)
EC <- pmax(EC, 0.02)

# ---- assemble ---------------------------------------------------------------

soil_structured <- data.frame(
  SampleID = paste0("STR", sprintf("%03d", seq_len(n))),
  Sand = round(Sand, 1),
  Silt = round(Silt, 1),
  Clay = round(Clay, 1),
  BD   = round(BD, 2),
  pH   = round(pH, 1),
  OM   = round(OM, 2),
  SOC  = round(SOC, 2),
  N    = round(N, 3),
  P    = round(P, 1),
  K    = round(K, 0),
  CEC  = round(CEC, 1),
  Ca   = round(Ca, 2),
  Mg   = round(Mg, 2),
  S    = round(S, 1),
  EC   = round(EC, 2),
  stringsAsFactors = FALSE
)

# Re-close the texture after rounding, so Sand + Silt + Clay is exactly 100.
soil_structured$Silt <- round(100 - soil_structured$Sand -
                                soil_structured$Clay, 1)

stopifnot(
  all(abs(soil_structured$Sand + soil_structured$Silt +
            soil_structured$Clay - 100) < 1e-8),
  !anyNA(soil_structured)
)

usethis::use_data(soil_structured, overwrite = TRUE)
